# This is a basic workflow to help you get started with Actions

name: Build UI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
#    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install Requirements
      run: |
        cd web-ui
        yarn install --frozen-lockfile
        npm run build
        
        
    - name: Build
      run: |
        npm run build
        
    - name: Deploy to release-metadata branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: github-pages
        user_name: "build-bot"
        user_email: "github_bot@github.com"
        allow_empty_commit: false
        force_orphan: true
